# Setup CLI to run make clean, build, test when the repo is cloned.
name: Clone jmim repository.
on: fork
jobs:
  clone:
    runs-on: macos-latest
    steps:
      - name: Clone repository to local machine
        uses: actions/checkout@main
        with:
          repository: 'DeraUchenwoke/jmim'